name: Push rapidocr_layout to pypi

on:
  push:
    branches: [ main ]
    paths:
      - 'rapid_layout/**'
      - 'docs/doc_whl_rapid_layout.md'
      - 'setup_layout.py'
      - '.github/workflows/gen_whl_to_pypi_rapid_layout.yml'
      - 'tests/test_layout.py'

env:
  RESOURCES_URL: https://github.com/RapidAI/RapidStructure/releases/download/v0.0.0/rapid_layout_models.zip

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Unit testings
        run: |
          wget $RESOURCES_URL
          ZIP_NAME=${RESOURCES_URL##*/}
          DIR_NAME=${ZIP_NAME%.*}

          unzip $DIR_NAME
          cp $DIR_NAME/*.onnx rapid_layout/models/
          pip install -r requirements.txt
          pytest tests/test_layout.py

  GenerateWHL_PushPyPi:
    needs: UnitTesting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run setup
        run: |
          pip install -r requirements.txt
          wget $RESOURCES_URL
          ZIP_NAME=${RESOURCES_URL##*/}
          DIR_NAME=${ZIP_NAME%.*}
          unzip $ZIP_NAME
          mv $DIR_NAME/*.onnx rapid_layout/models/
          python setup_layout.py bdist_wheel ${{ github.event.head_commit.message }}

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.RAPID_STRUCTURE }}
          packages_dir: dist/
