name: Push rapidocr_orientation to pypi

on:
  push:
    tags:
      - v*


env:
  RESOURCES_URL: https://github.com/RapidAI/RapidStructure/releases/download/v0.0.0/rapid_orientation_models.zip

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Unit testings
        run: |
          wget $RESOURCES_URL
          ZIP_NAME=${RESOURCES_URL##*/}
          DIR_NAME=${ZIP_NAME%.*}
          unzip $ZIP_NAME
          rm rapid_orientation/models/.gitkeep
          mv $DIR_NAME/*.onnx rapid_orientation/models/
          pip install -r requirements.txt
          pytest tests/test_orientation.py

  GenerateWHL_PushPyPi:
    needs: UnitTesting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Run setup
        run: |
          pip install -r requirements.txt
          wget $RESOURCES_URL
          ZIP_NAME=${RESOURCES_URL##*/}
          DIR_NAME=${ZIP_NAME%.*}
          unzip $ZIP_NAME
          mv $DIR_NAME/*.onnx rapid_orientation/models/
          python setup_orientation.py bdist_wheel ${{ github.ref_name }}

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.RAPID_STRUCTURE }}
          packages_dir: dist/
